project02/haddock/urls.py
from django.urls import path

from . import views

app_name = 'haddock'
urlpatterns = [
    path('', views.index, name='index'),
    path('registro/', views.telaregistro, name='telaregistro'),
    path('what/', views.what, name='what'),
    path('equipe/', views.equipe, name='equipe'),
    path('how/', views.how, name='how'),
    path('requisicao/', views.requisicao, name='requisicao'),
    path('login/',views.login_view, name='login_view'),
]

project02/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

project02/project02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('haddock/', include('haddock.urls')),
    path('admin/', admin.site.urls),
]

project02/haddock/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Incidente(models.Model):
    tipo = models.CharField(max_length=200)

class Criticidade(models.Model):
    nivel = models.IntegerField()
    descricao = models.CharField(max_length=200)

class Areas(models.Model):
    area = models.CharField(max_length=100)
    Coord = models.CharField(max_length=1000)

class UserData(models.Model):
    user = models.CharField(max_length=30)
    grupo = models.CharField(max_length=30)
    area = models.CharField(max_length=30)
    mobile = models.IntegerField()
class Registro(models.Model):
    resolvido = models.CharField(max_length=30)
    criador = models.CharField(max_length=30)
    pub_date = models.DateTimeField('date published')
    area = models.CharField(max_length=100)
    localizacao = models.CharField(max_length=300)
    criticidade = models.IntegerField()
    incidente=models.CharField(max_length=300,default='0000000')
    nivel=models.IntegerField(default=0)

project02/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

project02/haddock/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django_user_agents.utils import get_user_agent
from django.contrib import auth
from django.urls import reverse
from .models import Incidente, Criticidade,Areas,UserData,Registro
from django.utils import timezone
import requests
import os
from twilio.rest import Client


# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader


def index(request):
    user_agent = get_user_agent(request)
    if user_agent.is_mobile:
        template=loader.get_template('haddock/index.html')
        context={}
    else:
        template = loader.get_template('haddock/indexdesktop.html') 
        context = { }
    return HttpResponse(template.render(context, request))

def telaregistro(request):
    template = loader.get_template('haddock/telaregistro.html')
    incidente=Incidente.objects.order_by('-id')
    criticidade=Criticidade.objects.order_by('-id')
    context = { 'incidente':incidente, 'criticidade':criticidade}
    a=request.user.get_username




    return HttpResponse(template.render(context, request))

def equipe(request):
    template = loader.get_template('haddock/equipe.html') 
    context = { }
    return HttpResponse(template.render(context, request))

def how(request):
    template = loader.get_template('haddock/how.html') 
    context = { }
    return HttpResponse(template.render(context, request))

def what(request):
    template = loader.get_template('haddock/what.html') 
    context = { }
    return HttpResponse(template.render(context, request))


def login_view(request):
    user=auth.authenticate(username='hackathon',password='password')
    auth.login(request,user)
    return HttpResponseRedirect(reverse('haddock:telaregistro'))

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('haddock:index'))

def requisicao(request): 
    try:
        selected_incidente = Incidente.objects.get(pk=request.POST['respincidente'])
        selected_criticidade = Criticidade.objects.get(pk=request.POST['respcriticidade'])
    except (KeyError, Incidente.DoesNotExist):
        return HttpResponse(template.render(context, request))
    else:
        registrar=Registro(resolvido="False", criador=request.user.get_username, pub_date=timezone.now(),area=" ", localizacao=" ",criticidade=selected_criticidade.nivel,incidente=selected_incidente.tipo,nivel=0)
        registrar.save()

        a=selected_incidente.tipo
        b=selected_criticidade.nivel
        c=" "

        headers = {'content-type':'application/json','Authorization':'Bearer af8df04726988bf2eca0e0a1a763fa283279bb1f1d1b2f4fe2dd0d122eb265f6'}
        data = {'from':'0x557F81f0BD7f8cA83e06811f8a90F4A6b9a3Ca20','to':'0x557F81f0BD7f8cA83e06811f8a90F4A6b9a3Ca20','value':0,'data':'incident:{incidente},criticidade:{crit},localizacao:{loc}'.format(incidente=a,crit=b,loc=c),'pk':'0xd4ae53f91d65f7c2fa07a8cb8afba18e48b3160dcf9fb386ac9019268839123a','estimatedGas':'false'}

        request = requests.post('http://portohack.rbiblockchain.io/stcpconnector/registerdata', headers=headers,json=data)

        # Your Account SID from twilio.com/console
        account_sid = "AC293eb75e040f4b3b7bac23a6a23b255b"
        # Your Auth Token from twilio.com/console
        auth_token  = "1dd041ca5e10cb4f41912a44596ba2c0"

        client = Client(account_sid, auth_token)

        # this is the Twilio sandbox testing number
        from_whatsapp_number='whatsapp:+14155238886'
        # replace this number with your own WhatsApp Messaging number
        to_whatsapp_number='whatsapp:+5511963964336'

        client.messages.create(body='Você está sendo solicitado na área 3 terminal 27. Registro de: '+a+' em nível '+str(b)+'.',
                       from_=from_whatsapp_number,
                       to=to_whatsapp_number)

    return HttpResponseRedirect(reverse('haddock:index'))

project02/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Question, Choice
from django.urls import reverse

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

project02/haddock/templates/haddock/equipe.html
{% load static %}

<!DOCTIPE html>
<html lang="pt">
<head>
        <meta name="viewport" content="width=device-width, user-scalable=no">

    <link rel="stylesheet" href="{% static 'haddock/style1.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'haddock/images/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <title>Haddock</title>
    <style>
        body {
    background-image: url("{% static 'haddock/images/porto-de-containers.jpg' %}");
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    background-position: center;
    background-position-y: 10.5vh;
        }
        </style>
</head>
<body>
<header>
<div class="header">

    <div class="logo">

        <span class="helper"></span>
        <img src="{% static 'haddock/images/logo7.png' %}">
    </div>
    <div class="menu">
            <div class="menuside">
            </br>
                <input type="button" class="button" value="Login"></input>
                <a href="#">Home</a>
                <a href="#">O que é?</a>
    <a href="#">Como funciona?</a>
    <a href="#">Equipe</a>
            </div>

    <span class="helper"></span><i class="fa fa-bars"></i>
    </div>
</div>
</header>

<div class="conteudo">
        
    <ul class="equipe">
    <li class="equipe">
    <img src="img/qrteste.png">
    </br>
        <mark>&nbsp <i class="fa fa-linkedin-square"></i>  Alvaro Spinola &nbsp</mark></br></br></li>

    <li class="equipe">
    <img src="img/qrteste.png">
    </br>
        <mark>&nbsp <i class="fa fa-linkedin-square"></i>  Bruna Seixas &nbsp</mark></br></br></li>
    <li class="equipe">
            <img src="img/qrteste.png">
            </br>
            <mark>&nbsp <i class="fa fa-linkedin-square"></i>  Fernanda Silva &nbsp</mark></br></br></li>
    <li class="equipe">
            <img src="img/qrteste.png">
            </br>
            <mark>&nbsp <i class="fa fa-linkedin-square"></i>  Hugo Bolognesi &nbsp</mark></br></br></li>
    <li class="equipe">
            <img src="img/qrteste.png">
            </br>
            <mark>&nbsp <i class="fa fa-linkedin-square"></i>  Lucas Timoteo &nbsp</mark></br></br></li>
    <li class="equipe">
            <img src="img/qrteste.png">
            </br>
            <mark>&nbsp <i class="fa fa-linkedin-square"></i>  Marcos Fiuza &nbsp</mark></br></br></li>

</ul>

</div>

</body>
</html>

project02/haddock/templates/haddock/index.html
{% load static %}

<!DOCTIPE html>
<html lang="pt">
<head>
        <meta name="viewport" content="width=device-width, user-scalable=no">

    <link rel="stylesheet" href="{% static 'haddock/style1.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'haddock/images/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <title>Haddock</title>
    <style>
        body {
    background-image: url("{% static 'haddock/images/porto-de-containers.jpg' %}");
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    background-position: center;
    background-position-y: 10.5vh;
        }
        </style>
</head>
<body>
<header>
<div class="header">

    <div class="logo">

        <span class="helper"></span>
        <img src="{% static 'haddock/images/logo7.png' %}">
    </div>
    <div class="menu">
            <div class="menuside">
            </br>
<form action="{% url 'haddock:telaregistro' %}">
                <input type="submit" class="button" value="EMERGÊNCIA"></input>
</form>
                <a href="{% url 'haddock:what' %}">O que é?</a>
    <a href="{% url 'haddock:how' %}">Como funciona?</a>
    <a href="{% url 'haddock:equipe' %}">Equipe</a>
            </div>

    <span class="helper"></span><i class="fa fa-bars"></i>
    </div>
</div>
</header>


<div id="textoboasvindas">

</br>
<mark>Acesse a plataforma e </br>conheça nossas soluções!</mark>
</br>

</br>
<a href="{% url 'haddock:telaregistro' %}" ><mark>SAFETY FIRST</mark></a>

</div>


<div class="slantedDivA">
        <p class="welcome">
BEM-VINDO!
        </p>
</div>
</body>
</html>

project02/haddock/templates/haddock/index2.html
{% load leaflet_tags %}
<html>
  <head>
    {% leaflet_js %}
    {% leaflet_css %}
    <style>
      .leaflet-container { height: 100%; }
    </style>
    <script type="text/javascript">
    function map_init_basic (map, options) {
        L.marker([50.5, 30.5]).addTo(map);
    }
    </script>
  </head>
  <body>
    <h1>Mushrooms Spots</h1>
{% leaflet_map "yourmap" callback="window.map_init_basic" %}
  </body>
</html>

project02/haddock/templates/haddock/indexdesktop.html
{% load static %}

<!DOCTIPE html>
<html lang="pt">
<head>
    <style>
        body {
            background-image: linear-gradient(to bottom right, #242661, black);
            font-family: verdana;
            color: white;
            font-size: 300%;
        }
        .logo {
            margin: 2vw;
        }
        div {
            margin-left: 5vw;
            width: 90vw;
        }
        div.smile {
            text-align: center;
            font-size: 100%;
        }
        p {
            font-size: 60%;
        }
        .qr {
            display: block;
            margin: auto;
        }
    </style>
    <title>Haddock</title>
</head>
<body>
    <img class="logo" src="{% static 'haddock/images/logo7.png' %}" height="50vh"></img>
    </br>
    <div>
        Olá amig@! Por enquanto apenas nossa versão mobile está em operação.</br>
        <p>Acesse este site pelo celular ou escaneie o QR Code:</p>
    </div>
    <div>
        <img class="qr" src="{% static 'haddock/images/qrcode.png' %}"> </img>
    </div>
    </br>
    <div class="smile">
        :)
    </div>
</body>
</html>

project02/haddock/templates/haddock/tela_registro.html
{% load static %}

<!DOCTIPE html>
<html lang="pt">
<head>
        <meta name="viewport" content="width=device-width, user-scalable=no">

    <link rel="stylesheet" href="{% static 'haddock/style1.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'haddock/images/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <title>Haddock</title>
    <script src="{% static 'haddock/external.js' %}" type="text/javascript">
</head>
<body>
<header>
<div class="header">

    <div class="logo">

        <span class="helper"></span>
        <img src="/img/logo7.png"/>
    </div>
    <div class="menu">
            <div class="menuside"
            </br>
                <input type="button" class="button" value="Login"></input>
                <a href="#">Home</a>
                <a href="#">O que é?</a>
    <a href="#">Como funciona?</a>
    <a href="#">Equipe</a>
            </div>

    <span class="helper"></span><i class="fa fa-bars"></i>
    </div>
</div>
</header>

<main>
    <div class="mainpage">
        <form action="{% url 'haddock:requisicao'  %}" method="post">
{% csrf_token %}
<select name="respincidente">
    {% for tipo in incidente %}
        <option value="{{tipo.id}}">{{tipo.tipo}}</option>
    {% endfor %}
</select>
<select name="respcriticidade">
    {% for descricao in criticidade %}
        <option value="{{descricao.id}}">{{descricao.descricao}}</option>
    {% endfor %}
</select>
<input type="submit" value="Seleção">
</form>
<p>{{a}}</p>    



</div>
</main>



<footer>
<div class="foot">
<div class="active"><span class="helper"></span><i class="fa fa-map-marker"></i><br><p style="font-size: 10%;">Mapa</p></div>
<div class="footbutton"><span class="helper"></span><i class="fa fa-file-text"></i></div>
<div class="footbutton"><span class="helper"></span><i class="fa fa-fire-extinguisher"></i></div>
</div>
</div>
</footer>

</body>
</html>

project02/haddock/templates/haddock/telaregistro.html
{% load static %}

<!DOCTIPE html>
<html lang="pt">
<head>
        <meta name="viewport" content="width=device-width, user-scalable=no">

    <link rel="stylesheet" href="{% static 'haddock/style1.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'haddock/images/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <title>Haddock</title>
    <script src="external.js" type="text/javascript" defer></script>
</head>
<body>
<header>
<div class="header">

    <div class="logo">

        <span class="helper"></span>
        <img src="{% static 'haddock/images/logo7.png' %}"/>
    </div>
    <div class="menu">
            <div class="menuside">
            </br>
</br>
                <a href="{% url 'haddock:index' %}">Home</a>
                <a href="{% url 'haddock:what' %}">O que é?</a>
    <a href="{% url 'haddock:how' %}">Como funciona?</a>
    <a href="{% url 'haddock:equipe' %}">Equipe</a>
            </div>

    <span class="helper"></span><i class="fa fa-bars"></i>
    </div>
</div>
</header>

<main>
    <div class="mainpage-data">
         <form action="{% url 'haddock:requisicao'  %}" method="post">
{% csrf_token %}
</br>
Reporte aqui a ocorrência
</br>
</br>
Incidente:  &nbsp
<select class="button" style="font-size:3vmin; padding: 10px 15px"  name="respincidente">
    {% for tipo in incidente %}
        <option value="{{tipo.id}}">{{tipo.tipo}}</option>
    {% endfor %}
</select>
</br>
</br>
Nível crítico: &nbsp
<select class="button" style="font-size:3vmin; padding: 10px 15px" name="respcriticidade">
    {% for descricao in criticidade %}
        <option value="{{descricao.id}}">{{descricao.descricao}}</option>
    {% endfor %}
</select>
</br>
</br>
<input type="submit" class="button" style="background-color: rgb(201, 99, 99)" value="Enviar incidente">
</form>
<p>{{a}}</p>    

</div>

</main>



<footer>
<div class="foot">
<div class="footbutton"><span class="helper"></span><i class="fa fa-map-marker"></i><br><p style="font-size: 10%;">Mapa</p></div>
<div class="active"><span class="helper"></span><i class="fa fa-file-text"></i></div>
<div class="footbutton"><span class="helper"></span><i class="fa fa-fire-extinguisher"></i></div>
</div>
</div>
</footer>

</body>
</html>

project02/haddock/templates/haddock/what.html
{% load static %}

<!DOCTIPE html>
<html lang="pt">
<head>
        <meta name="viewport" content="width=device-width, user-scalable=no">

    <link rel="stylesheet" href="{% static 'haddock/style1.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'haddock/images/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <title>Haddock</title>
    <style>
        body {
    background-image: url("{% static 'haddock/images/porto-de-containers.jpg' %}");
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    background-position: center;
    background-position-y: 10.5vh;
        }
        </style>
</head>
<body>
<header>
<div class="header">

    <div class="logo">

        <span class="helper"></span>
        <img src="{% static 'haddock/images/logo7.png' %}">
    </div>
    <div class="menu">
            <div class="menuside">
            </br>
                <input type="button" class="button" value="Login"></input>
                <a href="#">Home</a>
                <a href="#">O que é?</a>
    <a href="#">Como funciona?</a>
    <a href="#">Equipe</a>
            </div>

    <span class="helper"></span><i class="fa fa-bars"></i>
    </div>
</div>
</header>


</body>
</html>

project02/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

project02/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

project02/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>